exports.seed = function (knex, Promise) {
  return knex('reviews').insert([
    { id: 1, content: 'Great Service! It saved my life.', rating: 5, user_id: 1, provider_id: 1 },
    { id: 2, content: 'This place could use some work.', rating: 2, user_id: 2, provider_id: 1 },
    { id: 3, content: 'I would go back in a heartbeat!', rating: 4, user_id: 3, provider_id: 1 },
    { id: 4, content: 'There are better options out there.', rating: 1, user_id: 4, provider_id: 1 },
    { id: 5, content: 'Great Service! It saved my life.', rating: 3, user_id: 5, provider_id: 1 },
    { id: 6, content: 'This place could use some work.', rating: 3, user_id: 6, provider_id: 2 },
    { id: 7, content: 'I would go back in a heartbeat!', rating: 5, user_id: 7, provider_id: 2 },
    { id: 8, content: 'There are better options out there.', rating: 5, user_id: 8, provider_id: 2 },
    { id: 9, content: 'Great Service! It saved my life.', rating: 4, user_id: 9, provider_id: 2 },
    { id: 10, content: 'This place could use some work.', rating: 1, user_id: 10, provider_id: 2 },
    { id: 11, content: 'I would go back in a heartbeat!', rating: 5, user_id: 1, provider_id: 3 },
    { id: 12, content: 'There are better options out there.', rating: 2, user_id: 2, provider_id: 3 },
    { id: 13, content: 'Great Service! It saved my life.', rating: 4, user_id: 3, provider_id: 3 },
    { id: 14, content: 'This place could use some work.', rating: 3, user_id: 4, provider_id: 3 },
    { id: 15, content: 'I would go back in a heartbeat!', rating: 4, user_id: 5, provider_id: 3 },
    { id: 16, content: 'There are better options out there.', rating: 3, user_id: 6, provider_id: 4 },
    { id: 17, content: 'Great Service! It saved my life.', rating: 5, user_id: 7, provider_id: 4 },
    { id: 18, content: 'This place could use some work.', rating: 2, user_id: 8, provider_id: 4 },
    { id: 19, content: 'I would go back in a heartbeat!', rating: 4, user_id: 9, provider_id: 4 },
    { id: 20, content: 'There are better options out there.', rating: 3, user_id: 10, provider_id: 4 },
    { id: 21, content: 'Great Service! It saved my life.', rating: 4, user_id: 1, provider_id: 5 },
    { id: 22, content: 'This place could use some work.', rating: 2, user_id: 2, provider_id: 5 },
    { id: 23, content: 'I would go back in a heartbeat!', rating: 3, user_id: 3, provider_id: 5 },
    { id: 24, content: 'There are better options out there.', rating: 2, user_id: 4, provider_id: 5 },
    { id: 25, content: 'Great Service! It saved my life.', rating: 4, user_id: 5, provider_id: 5 },
    { id: 26, content: 'This place could use some work.', rating: 4, user_id: 6, provider_id: 6 },
    { id: 27, content: 'I would go back in a heartbeat!', rating: 5, user_id: 7, provider_id: 6 },
    { id: 28, content: 'There are better options out there.', rating: 4, user_id: 8, provider_id: 6 },
    { id: 29, content: 'Great Service! It saved my life.', rating: 3, user_id: 9, provider_id: 6 },
    { id: 30, content: 'This place could use some work.', rating: 4, user_id: 10, provider_id: 6 },
    { id: 31, content: 'I would go back in a heartbeat!', rating: 5, user_id: 1, provider_id: 7 },
    { id: 32, content: 'There are better options out there.', rating: 2, user_id: 2, provider_id: 7 },
    { id: 33, content: 'Great Service! It saved my life.', rating: 4, user_id: 3, provider_id: 7 },
    { id: 34, content: 'This place could use some work.', rating: 1, user_id: 4, provider_id: 7 },
    { id: 35, content: 'I would go back in a heartbeat!', rating: 5, user_id: 5, provider_id: 7 },
    { id: 36, content: 'There are better options out there.', rating: 1, user_id: 6, provider_id: 8 },
    { id: 37, content: 'Great Service! It saved my life.', rating: 2, user_id: 7, provider_id: 8 },
    { id: 38, content: 'This place could use some work.', rating: 4, user_id: 8, provider_id: 8 },
    { id: 39, content: 'I would go back in a heartbeat!', rating: 2, user_id: 9, provider_id: 8 },
    { id: 40, content: 'There are better options out there.', rating: 3, user_id: 10, provider_id: 8 },
    { id: 41, content: 'Great Service! It saved my life.', rating: 4, user_id: 1, provider_id: 9 },
    { id: 42, content: 'This place could use some work.', rating: 2, user_id: 2, provider_id: 9 },
    { id: 43, content: 'I would go back in a heartbeat!', rating: 5, user_id: 3, provider_id: 9 },
    { id: 44, content: 'There are better options out there.', rating: 4, user_id: 4, provider_id: 9 },
    { id: 45, content: 'Great Service! It saved my life.', rating: 3, user_id: 5, provider_id: 9 },
    { id: 46, content: 'This place could use some work.', rating: 4, user_id: 6, provider_id: 10 },
    { id: 47, content: 'I would go back in a heartbeat!', rating: 5, user_id: 7, provider_id: 10 },
    { id: 48, content: 'There are better options out there.', rating: 4, user_id: 8, provider_id: 10 },
    { id: 49, content: 'Great Service! It saved my life.', rating: 5, user_id: 9, provider_id: 10 },
    { id: 50, content: 'This place could use some work.', rating: 4, user_id: 10, provider_id: 10 },
    { id: 51, content: 'I would go back in a heartbeat!', rating: 5, user_id: 1, provider_id: 1 },
    { id: 52, content: 'There are better options out there.', rating: 2, user_id: 2, provider_id: 2 },
    { id: 53, content: 'Great Service! It saved my life.', rating: 3, user_id: 3, provider_id: 3 },
    { id: 54, content: 'This place could use some work.', rating: 4, user_id: 4, provider_id: 4 },
    { id: 55, content: 'I would go back in a heartbeat!', rating: 5, user_id: 5, provider_id: 5 },
    { id: 56, content: 'There are better options out there.', rating: 2, user_id: 6, provider_id: 11 },
    { id: 57, content: 'Great Service! It saved my life.', rating: 4, user_id: 7, provider_id: 11 },
    { id: 58, content: 'This place could use some work.', rating: 4, user_id: 8, provider_id: 11 },
    { id: 59, content: 'I would go back in a heartbeat!', rating: 5, user_id: 9, provider_id: 11 },
    { id: 60, content: 'There are better options out there.', rating: 3, user_id: 10, provider_id: 12 },
    { id: 61, content: 'Great Service! It saved my life.', rating: 4, user_id: 1, provider_id: 12 },
    { id: 62, content: 'This place could use some work.', rating: 1, user_id: 2, provider_id: 12 },
    { id: 63, content: 'This place could use some work.', rating: 4, user_id: 10, provider_id: 12 },
    { id: 64, content: 'I would go back in a heartbeat!', rating: 5, user_id: 1, provider_id: 13 },
    { id: 65, content: 'There are better options out there.', rating: 2, user_id: 2, provider_id: 13 },
    { id: 66, content: 'Great Service! It saved my life.', rating: 4, user_id: 3, provider_id: 13 },
    { id: 67, content: 'This place could use some work.', rating: 1, user_id: 4, provider_id: 13 },
    { id: 68, content: 'I would go back in a heartbeat!', rating: 5, user_id: 5, provider_id: 14 },
    { id: 69, content: 'There are better options out there.', rating: 1, user_id: 6, provider_id: 14 },
    { id: 70, content: 'Great Service! It saved my life.', rating: 2, user_id: 7, provider_id: 14 },
    { id: 71, content: 'This place could use some work.', rating: 4, user_id: 8, provider_id: 14 },
    { id: 72, content: 'I would go back in a heartbeat!', rating: 2, user_id: 9, provider_id: 15 },
    { id: 73, content: 'There are better options out there.', rating: 3, user_id: 10, provider_id: 15 },
    { id: 74, content: 'Great Service! It saved my life.', rating: 4, user_id: 1, provider_id: 15 },
    { id: 75, content: 'This place could use some work.', rating: 2, user_id: 2, provider_id: 15 },
    { id: 76, content: 'I would go back in a heartbeat!', rating: 5, user_id: 3, provider_id: 16 },
    { id: 77, content: 'There are better options out there.', rating: 4, user_id: 4, provider_id: 16 },
    { id: 78, content: 'Great Service! It saved my life.', rating: 3, user_id: 5, provider_id: 16 },
    { id: 79, content: 'This place could use some work.', rating: 4, user_id: 6, provider_id: 16 },
    { id: 80, content: 'I would go back in a heartbeat!', rating: 5, user_id: 7, provider_id: 17 },
    { id: 81, content: 'There are better options out there.', rating: 4, user_id: 8, provider_id: 17 },
    { id: 82, content: 'Great Service! It saved my life.', rating: 5, user_id: 9, provider_id: 17 },
    { id: 83, content: 'This place could use some work.', rating: 4, user_id: 10, provider_id: 17 },
    { id: 84, content: 'I would go back in a heartbeat!', rating: 5, user_id: 1, provider_id: 18 },
    { id: 85, content: 'There are better options out there.', rating: 2, user_id: 2, provider_id: 18 },
    { id: 86, content: 'Great Service! It saved my life.', rating: 3, user_id: 3, provider_id: 18 },
    { id: 87, content: 'This place could use some work.', rating: 4, user_id: 4, provider_id: 18 },
    { id: 88, content: 'I would go back in a heartbeat!', rating: 5, user_id: 5, provider_id: 19 },
    { id: 89, content: 'There are better options out there.', rating: 2, user_id: 6, provider_id: 19 },
    { id: 90, content: 'Great Service! It saved my life.', rating: 4, user_id: 7, provider_id: 19 },
    { id: 91, content: 'This place could use some work.', rating: 4, user_id: 8, provider_id: 19 },
    { id: 92, content: 'I would go back in a heartbeat!', rating: 5, user_id: 9, provider_id: 20 },
    { id: 93, content: 'There are better options out there.', rating: 3, user_id: 10, provider_id: 20 },
    { id: 94, content: 'Great Service! It saved my life.', rating: 4, user_id: 1, provider_id: 20 },
    { id: 95, content: 'This place could use some work.', rating: 1, user_id: 2, provider_id: 20 },
    { id: 96, content: 'This place could use some work.', rating: 1, user_id: 2, provider_id: 20 },
    { id: 97, content: 'Great Service! It saved my life.', rating: 2, user_id: 7, provider_id: 21 },
    { id: 98, content: 'This place could use some work.', rating: 4, user_id: 8, provider_id: 21 },
    { id: 99, content: 'I would go back in a heartbeat!', rating: 2, user_id: 9, provider_id: 21 },
    { id: 100, content: 'There are better options out there.', rating: 3, user_id: 10, provider_id: 21 },
    { id: 101, content: 'Great Service! It saved my life.', rating: 4, user_id: 1, provider_id: 22 },
    { id: 102, content: 'This place could use some work.', rating: 2, user_id: 2, provider_id: 22 },
    { id: 103, content: 'I would go back in a heartbeat!', rating: 5, user_id: 3, provider_id: 22 },
    { id: 104, content: 'There are better options out there.', rating: 4, user_id: 4, provider_id: 22 },
    { id: 105, content: 'Great Service! It saved my life.', rating: 3, user_id: 5, provider_id: 23 },
    { id: 106, content: 'This place could use some work.', rating: 4, user_id: 6, provider_id: 23 },
    { id: 107, content: 'I would go back in a heartbeat!', rating: 5, user_id: 7, provider_id: 23 },
    { id: 108, content: 'There are better options out there.', rating: 4, user_id: 8, provider_id: 23 },
    { id: 109, content: 'Great Service! It saved my life.', rating: 5, user_id: 9, provider_id: 23 },
    { id: 110, content: 'This place could use some work.', rating: 4, user_id: 10, provider_id: 24 },
    { id: 111, content: 'I would go back in a heartbeat!', rating: 5, user_id: 1, provider_id: 24 },
    { id: 112, content: 'There are better options out there.', rating: 2, user_id: 2, provider_id: 24 },
    { id: 113, content: 'Great Service! It saved my life.', rating: 3, user_id: 3, provider_id: 24 },
    { id: 114, content: 'This place could use some work.', rating: 4, user_id: 4, provider_id: 12 },
    { id: 115, content: 'I would go back in a heartbeat!', rating: 5, user_id: 5, provider_id: 13 },
    { id: 116, content: 'There are better options out there.', rating: 2, user_id: 6, provider_id: 14 },
    { id: 117, content: 'Great Service! It saved my life.', rating: 4, user_id: 7, provider_id: 16 },
    { id: 118, content: 'This place could use some work.', rating: 4, user_id: 8, provider_id: 15 },
    { id: 119, content: 'I would go back in a heartbeat!', rating: 5, user_id: 9, provider_id: 17 },
    { id: 120, content: 'There are better options out there.', rating: 3, user_id: 10, provider_id: 18 },
    { id: 121, content: 'Great Service! It saved my life.', rating: 4, user_id: 1, provider_id: 19 },
    { id: 122, content: 'This place could use some work.', rating: 1, user_id: 2, provider_id: 20 },
    { id: 123, content: 'This place could use some work.', rating: 1, user_id: 2, provider_id: 21 },
    { id: 124, content: 'Great Service! It saved my life.', rating: 5, user_id: 1, provider_id: 22 },
    { id: 125, content: 'This place could use some work.', rating: 2, user_id: 2, provider_id: 23 },
    { id: 126, content: 'I would go back in a heartbeat!', rating: 4, user_id: 3, provider_id: 24 },
    { id: 127, content: 'There are better options out there.', rating: 1, user_id: 4, provider_id: 25 },
    { id: 128, content: 'Great Service! It saved my life.', rating: 3, user_id: 5, provider_id: 26 },
    { id: 129, content: 'This place could use some work.', rating: 3, user_id: 6, provider_id: 27 },
    { id: 130, content: 'I would go back in a heartbeat!', rating: 5, user_id: 7, provider_id: 28 },
    { id: 131, content: 'There are better options out there.', rating: 5, user_id: 8, provider_id: 29 },
    { id: 132, content: 'Great Service! It saved my life.', rating: 4, user_id: 9, provider_id: 30 },
    { id: 133, content: 'This place could use some work.', rating: 1, user_id: 10, provider_id: 31 },
    { id: 134, content: 'I would go back in a heartbeat!', rating: 5, user_id: 1, provider_id: 32 },
    { id: 135, content: 'There are better options out there.', rating: 2, user_id: 2, provider_id: 33 },
    { id: 136, content: 'Great Service! It saved my life.', rating: 4, user_id: 3, provider_id: 34 },
    { id: 137, content: 'This place could use some work.', rating: 3, user_id: 4, provider_id: 35 },
    { id: 138, content: 'I would go back in a heartbeat!', rating: 4, user_id: 5, provider_id: 36 },
    { id: 139, content: 'There are better options out there.', rating: 3, user_id: 6, provider_id: 37 },
    { id: 140, content: 'Great Service! It saved my life.', rating: 5, user_id: 7, provider_id: 38 },
    { id: 141, content: 'This place could use some work.', rating: 2, user_id: 8, provider_id: 39 },
    { id: 142, content: 'I would go back in a heartbeat!', rating: 4, user_id: 9, provider_id: 40 },
    { id: 143, content: 'There are better options out there.', rating: 3, user_id: 10, provider_id: 41 },
    { id: 144, content: 'Great Service! It saved my life.', rating: 4, user_id: 1, provider_id: 42 },
    { id: 145, content: 'This place could use some work.', rating: 2, user_id: 2, provider_id: 43 },
    { id: 146, content: 'I would go back in a heartbeat!', rating: 3, user_id: 3, provider_id: 45 },
    { id: 147, content: 'There are better options out there.', rating: 2, user_id: 4, provider_id: 44 },
    { id: 148, content: 'Great Service! It saved my life.', rating: 4, user_id: 5, provider_id: 45 },
    { id: 149, content: 'This place could use some work.', rating: 4, user_id: 6, provider_id: 46 },
    { id: 150, content: 'I would go back in a heartbeat!', rating: 5, user_id: 7, provider_id: 47 },
    { id: 151, content: 'There are better options out there.', rating: 4, user_id: 8, provider_id: 48 },
    { id: 152, content: 'Great Service! It saved my life.', rating: 3, user_id: 9, provider_id: 49 },
    { id: 153, content: 'This place could use some work.', rating: 4, user_id: 10, provider_id: 50 },
    { id: 154, content: 'I would go back in a heartbeat!', rating: 5, user_id: 1, provider_id: 51 },
    { id: 155, content: 'There are better options out there.', rating: 2, user_id: 2, provider_id: 52 },
    { id: 156, content: 'Great Service! It saved my life.', rating: 4, user_id: 3, provider_id: 53 },
    { id: 157, content: 'This place could use some work.', rating: 1, user_id: 4, provider_id: 54 },
    { id: 158, content: 'I would go back in a heartbeat!', rating: 5, user_id: 5, provider_id: 55 },
    { id: 159, content: 'There are better options out there.', rating: 1, user_id: 6, provider_id: 56 },
    { id: 160, content: 'Great Service! It saved my life.', rating: 2, user_id: 7, provider_id: 57 },
    { id: 161, content: 'This place could use some work.', rating: 4, user_id: 8, provider_id: 58 },
    { id: 162, content: 'I would go back in a heartbeat!', rating: 2, user_id: 9, provider_id: 59 },
    { id: 163, content: 'There are better options out there.', rating: 3, user_id: 10, provider_id: 60 },
    { id: 164, content: 'Great Service! It saved my life.', rating: 4, user_id: 1, provider_id: 61 },
    { id: 165, content: 'This place could use some work.', rating: 2, user_id: 2, provider_id: 62 },
    { id: 166, content: 'I would go back in a heartbeat!', rating: 5, user_id: 3, provider_id: 63 },
    { id: 167, content: 'There are better options out there.', rating: 4, user_id: 4, provider_id: 64 },
    { id: 168, content: 'Great Service! It saved my life.', rating: 3, user_id: 5, provider_id: 65 },
    { id: 169, content: 'This place could use some work.', rating: 4, user_id: 6, provider_id: 66 },
    { id: 170, content: 'I would go back in a heartbeat!', rating: 5, user_id: 7, provider_id: 67 },
    { id: 171, content: 'There are better options out there.', rating: 4, user_id: 8, provider_id: 68 },
    { id: 172, content: 'Great Service! It saved my life.', rating: 5, user_id: 9, provider_id: 69 },
    { id: 173, content: 'This place could use some work.', rating: 4, user_id: 10, provider_id: 70 },
    { id: 174, content: 'I would go back in a heartbeat!', rating: 5, user_id: 1, provider_id: 71 },
    { id: 175, content: 'There are better options out there.', rating: 2, user_id: 2, provider_id: 72 },
    { id: 176, content: 'Great Service! It saved my life.', rating: 3, user_id: 3, provider_id: 1 },
    { id: 177, content: 'This place could use some work.', rating: 4, user_id: 4, provider_id: 2 },
    { id: 178, content: 'I would go back in a heartbeat!', rating: 5, user_id: 5, provider_id: 3 },
    { id: 179, content: 'There are better options out there.', rating: 2, user_id: 6, provider_id: 4 },
    { id: 180, content: 'Great Service! It saved my life.', rating: 4, user_id: 7, provider_id: 5 },
    { id: 181, content: 'This place could use some work.', rating: 4, user_id: 8, provider_id: 6 },
    { id: 182, content: 'I would go back in a heartbeat!', rating: 5, user_id: 9, provider_id: 7 },
    { id: 183, content: 'There are better options out there.', rating: 3, user_id: 10, provider_id: 8 },
    { id: 184, content: 'Great Service! It saved my life.', rating: 4, user_id: 1, provider_id: 9 },
    { id: 185, content: 'This place could use some work.', rating: 1, user_id: 2, provider_id: 10 },
    { id: 186, content: 'This place could use some work.', rating: 4, user_id: 10, provider_id: 11 },
    { id: 187, content: 'I would go back in a heartbeat!', rating: 5, user_id: 1, provider_id: 12 },
    { id: 188, content: 'There are better options out there.', rating: 2, user_id: 2, provider_id: 13 },
    { id: 189, content: 'Great Service! It saved my life.', rating: 4, user_id: 3, provider_id: 14 },
    { id: 190, content: 'This place could use some work.', rating: 1, user_id: 4, provider_id: 15 },
    { id: 191, content: 'I would go back in a heartbeat!', rating: 5, user_id: 5, provider_id: 17 },
    { id: 192, content: 'There are better options out there.', rating: 1, user_id: 6, provider_id: 18 },
    { id: 193, content: 'Great Service! It saved my life.', rating: 2, user_id: 7, provider_id: 19 },
    { id: 194, content: 'This place could use some work.', rating: 4, user_id: 8, provider_id: 20 },
    { id: 195, content: 'I would go back in a heartbeat!', rating: 2, user_id: 9, provider_id: 21 },
    { id: 196, content: 'There are better options out there.', rating: 3, user_id: 10, provider_id: 22 },
    { id: 197, content: 'Great Service! It saved my life.', rating: 4, user_id: 1, provider_id: 23 },
    { id: 198, content: 'This place could use some work.', rating: 2, user_id: 2, provider_id: 24 },
    { id: 199, content: 'I would go back in a heartbeat!', rating: 5, user_id: 3, provider_id: 25 },
    { id: 200, content: 'There are better options out there.', rating: 4, user_id: 4, provider_id: 26 },
    { id: 201, content: 'Great Service! It saved my life.', rating: 3, user_id: 5, provider_id: 27 },
    { id: 202, content: 'This place could use some work.', rating: 4, user_id: 6, provider_id: 28 },
    { id: 203, content: 'I would go back in a heartbeat!', rating: 5, user_id: 7, provider_id: 29 },
    { id: 204, content: 'There are better options out there.', rating: 4, user_id: 8, provider_id: 30 },
    { id: 205, content: 'Great Service! It saved my life.', rating: 5, user_id: 9, provider_id: 31 },
    { id: 206, content: 'This place could use some work.', rating: 4, user_id: 10, provider_id: 32 },
    { id: 207, content: 'I would go back in a heartbeat!', rating: 5, user_id: 1, provider_id: 33 },
    { id: 208, content: 'There are better options out there.', rating: 2, user_id: 2, provider_id: 34 },
    { id: 209, content: 'Great Service! It saved my life.', rating: 3, user_id: 3, provider_id: 35 },
    { id: 210, content: 'This place could use some work.', rating: 4, user_id: 4, provider_id: 36 },
    { id: 211, content: 'I would go back in a heartbeat!', rating: 5, user_id: 5, provider_id: 37 },
    { id: 212, content: 'There are better options out there.', rating: 2, user_id: 6, provider_id: 38 },
    { id: 213, content: 'Great Service! It saved my life.', rating: 4, user_id: 7, provider_id: 39 },
    { id: 214, content: 'This place could use some work.', rating: 4, user_id: 8, provider_id: 40 },
    { id: 215, content: 'I would go back in a heartbeat!', rating: 5, user_id: 9, provider_id: 41 },
    { id: 216, content: 'There are better options out there.', rating: 3, user_id: 10, provider_id: 42 },
    { id: 217, content: 'Great Service! It saved my life.', rating: 4, user_id: 1, provider_id: 43 },
    { id: 218, content: 'This place could use some work.', rating: 1, user_id: 2, provider_id: 44 },
    { id: 219, content: 'This place could use some work.', rating: 1, user_id: 2, provider_id: 45 },
    { id: 220, content: 'Great Service! It saved my life.', rating: 2, user_id: 7, provider_id: 46 },
    { id: 221, content: 'This place could use some work.', rating: 4, user_id: 8, provider_id: 47 },
    { id: 222, content: 'I would go back in a heartbeat!', rating: 2, user_id: 9, provider_id: 48 },
    { id: 223, content: 'There are better options out there.', rating: 3, user_id: 10, provider_id: 49 },
    { id: 224, content: 'Great Service! It saved my life.', rating: 4, user_id: 1, provider_id: 50 },
    { id: 225, content: 'This place could use some work.', rating: 2, user_id: 2, provider_id: 51 },
    { id: 226, content: 'I would go back in a heartbeat!', rating: 5, user_id: 3, provider_id: 52 },
    { id: 227, content: 'There are better options out there.', rating: 4, user_id: 4, provider_id: 53 },
    { id: 228, content: 'Great Service! It saved my life.', rating: 3, user_id: 5, provider_id: 54 },
    { id: 229, content: 'This place could use some work.', rating: 4, user_id: 6, provider_id: 55 },
    { id: 230, content: 'I would go back in a heartbeat!', rating: 5, user_id: 7, provider_id: 56 },
    { id: 231, content: 'There are better options out there.', rating: 4, user_id: 8, provider_id: 57 },
    { id: 232, content: 'Great Service! It saved my life.', rating: 5, user_id: 9, provider_id: 58 },
    { id: 234, content: 'This place could use some work.', rating: 4, user_id: 10, provider_id: 59 },
    { id: 235, content: 'I would go back in a heartbeat!', rating: 5, user_id: 1, provider_id: 60 },
    { id: 236, content: 'There are better options out there.', rating: 2, user_id: 2, provider_id: 61 },
    { id: 237, content: 'Great Service! It saved my life.', rating: 3, user_id: 3, provider_id: 62 },
    { id: 238, content: 'This place could use some work.', rating: 4, user_id: 4, provider_id: 63 },
    { id: 239, content: 'I would go back in a heartbeat!', rating: 5, user_id: 5, provider_id: 64 },
    { id: 240, content: 'There are better options out there.', rating: 2, user_id: 6, provider_id: 65 },
    { id: 241, content: 'Great Service! It saved my life.', rating: 4, user_id: 7, provider_id: 66 },
    { id: 242, content: 'This place could use some work.', rating: 4, user_id: 8, provider_id: 67 },
    { id: 243, content: 'I would go back in a heartbeat!', rating: 5, user_id: 9, provider_id: 68 },
    { id: 244, content: 'There are better options out there.', rating: 3, user_id: 10, provider_id: 69 },
    { id: 245, content: 'Great Service! It saved my life.', rating: 4, user_id: 1, provider_id: 70 },
    { id: 246, content: 'This place could use some work.', rating: 1, user_id: 2, provider_id: 71 },
    { id: 247, content: 'This place could use some work.', rating: 1, user_id: 2, provider_id: 72 },
    { id: 248, content: 'Great Service! It saved my life.', rating: 5, user_id: 1, provider_id: 1 },
    { id: 249, content: 'This place could use some work.', rating: 2, user_id: 2, provider_id: 1 },
    { id: 250, content: 'I would go back in a heartbeat!', rating: 4, user_id: 3, provider_id: 1 },
    { id: 251, content: 'There are better options out there.', rating: 1, user_id: 4, provider_id: 1 },
    { id: 252, content: 'Great Service! It saved my life.', rating: 3, user_id: 5, provider_id: 1 },
    { id: 253, content: 'This place could use some work.', rating: 3, user_id: 6, provider_id: 2 },
    { id: 254, content: 'I would go back in a heartbeat!', rating: 5, user_id: 7, provider_id: 2 },
    { id: 255, content: 'There are better options out there.', rating: 5, user_id: 8, provider_id: 2 },
    { id: 256, content: 'Great Service! It saved my life.', rating: 4, user_id: 9, provider_id: 2 },
    { id: 257, content: 'This place could use some work.', rating: 1, user_id: 10, provider_id: 2 },
    { id: 258, content: 'I would go back in a heartbeat!', rating: 5, user_id: 1, provider_id: 3 },
    { id: 259, content: 'There are better options out there.', rating: 2, user_id: 2, provider_id: 3 },
    { id: 260, content: 'Great Service! It saved my life.', rating: 4, user_id: 3, provider_id: 3 },
    { id: 261, content: 'This place could use some work.', rating: 3, user_id: 4, provider_id: 3 },
    { id: 262, content: 'I would go back in a heartbeat!', rating: 4, user_id: 5, provider_id: 3 },
    { id: 263, content: 'There are better options out there.', rating: 3, user_id: 6, provider_id: 4 },
    { id: 264, content: 'Great Service! It saved my life.', rating: 5, user_id: 7, provider_id: 4 },
    { id: 265, content: 'This place could use some work.', rating: 2, user_id: 8, provider_id: 4 },
    { id: 266, content: 'I would go back in a heartbeat!', rating: 4, user_id: 9, provider_id: 4 },
    { id: 267, content: 'There are better options out there.', rating: 3, user_id: 10, provider_id: 4 },
    { id: 268, content: 'Great Service! It saved my life.', rating: 4, user_id: 1, provider_id: 5 },
    { id: 269, content: 'This place could use some work.', rating: 2, user_id: 2, provider_id: 5 },
    { id: 270, content: 'I would go back in a heartbeat!', rating: 3, user_id: 3, provider_id: 5 },
    { id: 271, content: 'There are better options out there.', rating: 2, user_id: 4, provider_id: 5 },
    { id: 272, content: 'Great Service! It saved my life.', rating: 4, user_id: 5, provider_id: 5 },
    { id: 273, content: 'This place could use some work.', rating: 4, user_id: 6, provider_id: 6 },
    { id: 274, content: 'I would go back in a heartbeat!', rating: 5, user_id: 7, provider_id: 6 },
    { id: 275, content: 'There are better options out there.', rating: 4, user_id: 8, provider_id: 6 },
    { id: 276, content: 'Great Service! It saved my life.', rating: 3, user_id: 9, provider_id: 6 },
    { id: 277, content: 'This place could use some work.', rating: 4, user_id: 10, provider_id: 6 },
    { id: 278, content: 'I would go back in a heartbeat!', rating: 5, user_id: 1, provider_id: 7 },
    { id: 279, content: 'There are better options out there.', rating: 2, user_id: 2, provider_id: 7 },
    { id: 280, content: 'Great Service! It saved my life.', rating: 4, user_id: 3, provider_id: 7 },
    { id: 281, content: 'This place could use some work.', rating: 1, user_id: 4, provider_id: 7 },
    { id: 282, content: 'I would go back in a heartbeat!', rating: 5, user_id: 5, provider_id: 7 },
    { id: 283, content: 'There are better options out there.', rating: 1, user_id: 6, provider_id: 8 },
    { id: 284, content: 'Great Service! It saved my life.', rating: 2, user_id: 7, provider_id: 8 },
    { id: 285, content: 'This place could use some work.', rating: 4, user_id: 8, provider_id: 8 },
    { id: 286, content: 'I would go back in a heartbeat!', rating: 2, user_id: 9, provider_id: 8 },
    { id: 287, content: 'There are better options out there.', rating: 3, user_id: 10, provider_id: 8 },
    { id: 288, content: 'Great Service! It saved my life.', rating: 4, user_id: 1, provider_id: 9 },
    { id: 289, content: 'This place could use some work.', rating: 2, user_id: 2, provider_id: 9 },
    { id: 290, content: 'I would go back in a heartbeat!', rating: 5, user_id: 3, provider_id: 9 },
    { id: 291, content: 'There are better options out there.', rating: 4, user_id: 4, provider_id: 9 },
    { id: 292, content: 'Great Service! It saved my life.', rating: 3, user_id: 5, provider_id: 9 },
    { id: 293, content: 'This place could use some work.', rating: 4, user_id: 6, provider_id: 10 },
    { id: 294, content: 'I would go back in a heartbeat!', rating: 5, user_id: 7, provider_id: 10 },
    { id: 295, content: 'There are better options out there.', rating: 4, user_id: 8, provider_id: 10 },
    { id: 296, content: 'Great Service! It saved my life.', rating: 5, user_id: 9, provider_id: 10 },
    { id: 297, content: 'This place could use some work.', rating: 4, user_id: 10, provider_id: 10 },
    { id: 298, content: 'I would go back in a heartbeat!', rating: 5, user_id: 1, provider_id: 1 },
    { id: 299, content: 'There are better options out there.', rating: 2, user_id: 2, provider_id: 2 },
    { id: 300, content: 'Great Service! It saved my life.', rating: 3, user_id: 3, provider_id: 3 },
    { id: 301, content: 'This place could use some work.', rating: 4, user_id: 4, provider_id: 4 },
    { id: 302, content: 'I would go back in a heartbeat!', rating: 5, user_id: 5, provider_id: 5 },
    { id: 303, content: 'There are better options out there.', rating: 2, user_id: 6, provider_id: 5 },
    { id: 304, content: 'Great Service! It saved my life.', rating: 4, user_id: 7, provider_id: 6 },
    { id: 305, content: 'This place could use some work.', rating: 4, user_id: 8, provider_id: 7 },
    { id: 306, content: 'I would go back in a heartbeat!', rating: 5, user_id: 9, provider_id: 8 },
    { id: 307, content: 'There are better options out there.', rating: 3, user_id: 10, provider_id: 9 },
    { id: 308, content: 'Great Service! It saved my life.', rating: 4, user_id: 1, provider_id: 10 },
    { id: 309, content: 'This place could use some work.', rating: 1, user_id: 2, provider_id: 11 },
    { id: 310, content: 'This place could use some work.', rating: 4, user_id: 10, provider_id: 12 },
    { id: 311, content: 'I would go back in a heartbeat!', rating: 5, user_id: 1, provider_id: 13 },
    { id: 312, content: 'There are better options out there.', rating: 2, user_id: 2, provider_id: 14 },
    { id: 313, content: 'Great Service! It saved my life.', rating: 4, user_id: 3, provider_id: 15 },
    { id: 314, content: 'This place could use some work.', rating: 1, user_id: 4, provider_id: 16 },
    { id: 315, content: 'I would go back in a heartbeat!', rating: 5, user_id: 5, provider_id: 17 },
    { id: 316, content: 'There are better options out there.', rating: 1, user_id: 6, provider_id: 18 },
    { id: 317, content: 'Great Service! It saved my life.', rating: 2, user_id: 7, provider_id: 19 },
    { id: 318, content: 'This place could use some work.', rating: 4, user_id: 8, provider_id: 20 },
    { id: 319, content: 'I would go back in a heartbeat!', rating: 2, user_id: 9, provider_id: 21 },
    { id: 320, content: 'There are better options out there.', rating: 3, user_id: 10, provider_id: 22 },
    { id: 321, content: 'Great Service! It saved my life.', rating: 4, user_id: 1, provider_id: 23 },
    { id: 322, content: 'This place could use some work.', rating: 2, user_id: 2, provider_id: 24 },
    { id: 323, content: 'I would go back in a heartbeat!', rating: 5, user_id: 3, provider_id: 25 },
    { id: 324, content: 'There are better options out there.', rating: 4, user_id: 4, provider_id: 26 },
    { id: 325, content: 'Great Service! It saved my life.', rating: 3, user_id: 5, provider_id: 27 },
    { id: 326, content: 'This place could use some work.', rating: 4, user_id: 6, provider_id: 28 },
    { id: 327, content: 'I would go back in a heartbeat!', rating: 5, user_id: 7, provider_id: 29 },
    { id: 328, content: 'There are better options out there.', rating: 4, user_id: 8, provider_id: 30 },
    { id: 329, content: 'Great Service! It saved my life.', rating: 5, user_id: 9, provider_id: 31 },
    { id: 330, content: 'This place could use some work.', rating: 4, user_id: 10, provider_id: 32 },
    { id: 331, content: 'I would go back in a heartbeat!', rating: 5, user_id: 1, provider_id: 33 },
    { id: 332, content: 'There are better options out there.', rating: 2, user_id: 2, provider_id: 34 },
    { id: 333, content: 'Great Service! It saved my life.', rating: 3, user_id: 3, provider_id: 35 },
    { id: 334, content: 'This place could use some work.', rating: 4, user_id: 4, provider_id: 36 },
    { id: 335, content: 'I would go back in a heartbeat!', rating: 5, user_id: 5, provider_id: 37 },
    { id: 336, content: 'There are better options out there.', rating: 2, user_id: 6, provider_id: 38 },
    { id: 337, content: 'Great Service! It saved my life.', rating: 4, user_id: 7, provider_id: 39 },
    { id: 338, content: 'This place could use some work.', rating: 4, user_id: 8, provider_id: 40 },
    { id: 339, content: 'I would go back in a heartbeat!', rating: 5, user_id: 9, provider_id: 41 },
    { id: 340, content: 'There are better options out there.', rating: 3, user_id: 10, provider_id: 42 },
    { id: 341, content: 'Great Service! It saved my life.', rating: 4, user_id: 1, provider_id: 43 },
    { id: 342, content: 'This place could use some work.', rating: 1, user_id: 2, provider_id: 44 },
    { id: 343, content: 'This place could use some work.', rating: 1, user_id: 2, provider_id: 45 },
    { id: 344, content: 'Great Service! It saved my life.', rating: 2, user_id: 7, provider_id: 46 },
    { id: 345, content: 'This place could use some work.', rating: 4, user_id: 8, provider_id: 47 },
    { id: 346, content: 'I would go back in a heartbeat!', rating: 2, user_id: 9, provider_id: 48 },
    { id: 347, content: 'There are better options out there.', rating: 3, user_id: 10, provider_id: 49 },
    { id: 348, content: 'Great Service! It saved my life.', rating: 4, user_id: 1, provider_id: 50 },
    { id: 349, content: 'This place could use some work.', rating: 2, user_id: 2, provider_id: 51 },
    { id: 350, content: 'I would go back in a heartbeat!', rating: 5, user_id: 3, provider_id: 52 },
    { id: 351, content: 'There are better options out there.', rating: 4, user_id: 4, provider_id: 53 },
    { id: 352, content: 'Great Service! It saved my life.', rating: 3, user_id: 5, provider_id: 54 },
    { id: 353, content: 'This place could use some work.', rating: 4, user_id: 6, provider_id: 55 },
    { id: 354, content: 'I would go back in a heartbeat!', rating: 5, user_id: 7, provider_id: 56 },
    { id: 355, content: 'There are better options out there.', rating: 4, user_id: 8, provider_id: 57 },
    { id: 356, content: 'Great Service! It saved my life.', rating: 5, user_id: 9, provider_id: 58 },
    { id: 357, content: 'This place could use some work.', rating: 4, user_id: 10, provider_id: 59 },
    { id: 358, content: 'I would go back in a heartbeat!', rating: 5, user_id: 1, provider_id: 60 },
    { id: 359, content: 'There are better options out there.', rating: 2, user_id: 2, provider_id: 61 },
    { id: 360, content: 'Great Service! It saved my life.', rating: 3, user_id: 3, provider_id: 62 },
    { id: 361, content: 'This place could use some work.', rating: 4, user_id: 4, provider_id: 63 },
    { id: 362, content: 'I would go back in a heartbeat!', rating: 5, user_id: 5, provider_id: 64 },
    { id: 363, content: 'There are better options out there.', rating: 2, user_id: 6, provider_id: 65 },
    { id: 364, content: 'Great Service! It saved my life.', rating: 4, user_id: 7, provider_id: 66 },
    { id: 365, content: 'This place could use some work.', rating: 4, user_id: 8, provider_id: 67 },
    { id: 366, content: 'I would go back in a heartbeat!', rating: 5, user_id: 9, provider_id: 68 },
    { id: 367, content: 'There are better options out there.', rating: 3, user_id: 10, provider_id: 69 },
    { id: 368, content: 'Great Service! It saved my life.', rating: 4, user_id: 1, provider_id: 70 },
    { id: 369, content: 'This place could use some work.', rating: 1, user_id: 2, provider_id: 71 },
    { id: 370, content: 'This place could use some work.', rating: 1, user_id: 2, provider_id: 72 }
  ])
    .then(() => {
      return knex.raw("SELECT setval('reviews_id_seq', (SELECT MAX(id) FROM reviews));")
    })
}
